---
title: "ino: Initialization of Numerical Optimization in R"
abstract: >
  Numerical optimization of some target functions is of great relevance in many fields, as many optimization problems cannot be solved analytically. While R provides several functions for applying numerical optimization, such as `nlm()` or `optim()` from the stats package, users have to select initial values when applying such methods. Since the choice of initial values can hugely affect the convergence time and rate, several strategies exist for selecting initial values. The ino package provides a toolbox for evaluating the effect of the initial values on the optimization as well as comparing different initialization strategies and optimizers.
draft: true
author:  
  # see ?rjournal_article for more information
  - name: Lennart Oelschl&#228;ger
    affiliation: Bielefeld University
    address:
    - Department of Business Administration and Economics
    - Bielefeld, Germany
    url: https://loelschlaeger.de/
    #orcid: 0000-1721-1511-1101
    email:  lennart.oelschlaeger@uni-bielefeld.de
  - name: Marius &#214;tting
    url: https://www.uni-bielefeld.de/fakultaeten/wirtschaftswissenschaften/lehrbereiche/stats/team/marius-otting-(m.sc.)/
    email: marius.oetting@uni-bielefeld.de
    orcid: 0000-0002-9373-0365
    affiliation: Bielefeld University
    address:
    - Department of Business Administration and Economics
    - Bielefeld, Germany
type: package
output: 
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
bibliography: RJreferences.bib

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(ggplot2)
library(dplyr)
library(purrr)
library(ino)
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

# Introduction



# A brief background on numerical optimization

```{r plot_ackley}
### optimize Ackley function with different starting values
opt_results <- data.frame(Var1 = c(4.8, 3, 2, 1),
                          Var2 = c(4.8, 3, 4, 5)) %>% 
  mutate(input_vec = map2(Var1, Var2, ~c(.x, .y))) %>% 
  mutate(opt_x = map_dbl(input_vec, ~nlm(f_ackley, .x)$estimate[1])) %>% 
  mutate(opt_y = map_dbl(input_vec, ~nlm(f_ackley, .x)$estimate[2])) %>% 
  mutate(opt_value = map_dbl(input_vec, ~nlm(f_ackley, .x)$minimum)) %>% 
  mutate(opt_run = 1:4) %>% 
  mutate(z_value_start = map_dbl(input_vec, f_ackley))

## plotting
val1 <- val2 <- seq(-5, 5, 0.1)
data_plot <- expand.grid(val1, val2) %>% 
  mutate(x = map2(Var1, Var2, ~c(.x, .y))) %>% 
  mutate(z = map_dbl(x, f_ackley))


ggplot(data_plot, aes(x = Var1, y = Var2, z = z)) +
  geom_contour_filled() +
  theme_minimal() + xlab("x") + ylab("y") +
  theme(legend.title = element_blank()) +
  geom_point(data = opt_results, aes(x = opt_x, y = opt_y, 
                                     z = opt_value, colour = factor(opt_run)),
             size = 5, shape = 21, stroke = 2) +
  geom_point(data = opt_results, aes(x = Var1, y = Var2, 
                                     z = z_value_start, colour = factor(opt_run)),
             size = 5, shape = 4, stroke = 2) +
  scale_colour_manual(values = cbPalette[c(1,2,3,7)], guide = "none")
```


## Numerical optimization

## Strategies for choosing initial values 

# Usage of {ino}

## Implementation of strategies for choosing initial values 

## Application to mixture models

## Application to hidden Markov models

## Application to multinomial probit models

# Discussion


